services:
  mbakmegumi:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbakmegumi
    image: haikelilham/mbakmegumi:latest
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
