apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mbakmegumi
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: mbakmegumi.ekel.dev
      http:
        paths:
          - path: /
            pathType: prefix
            backend:
              service:
                name: mbakmegumi
                port:
                  number: 80
